### ISSUE TITLE
项目很好，试验成功。但这里有个需求，不知能否实现。

### ISSUE THREAD

**Issue by xxp2277** [ndroi/easy163#10]
魅族flyme 7试验成功。
但这里有个需求，希望帮忙解答下实现的难度：现在安卓手机使用SSR连回家里路由器的SSR服务端实现免流+科学上网，使用本软件由于新建vpn了会导致手机端原来的ssr退出而无法免流和科学上网。我在https://github.com/coolsnowwolf/lede/issues/4679 问过SSR回连到路由器同时利用路由器的解锁音乐是否可行，答案是否定的。但是我在楼主这里好像看见了希望，感觉https://github.com/ndroi/easy163/issues/3 说的自定义服务器要是实现了将服务器放到路由器或者vps中，再用ssr之类去连接好像是可行的？小白一个，不知道这个做起来是否真的难度很大？或者是由于ssr本身混淆的功能和解锁音乐的功能是冲突的？

**Comment by ndroi** [comment]
我也不太了解，只知道有解锁网易云的路由器插件。

**Comment by xxp2277** [comment]
好的，感谢解答。
