### ISSUE TITLE
安卓10，安装桌面无应用图标，本人手机一加7t pro！

### ISSUE THREAD

**Issue by snakwu** [ndroi/easy163#17]
安卓10，安装桌面无应用图标，本人手机一加7t pro！

**Comment by ndroi** [comment]
设置里可以找到吗？
安装完毕能够直接打开吗？

**Comment by snakwu** [comment]
@ndroi  设置，应用里可找到，可打开，但桌面澡有图标，只能在设置里面来打开

**Comment by ndroi** [comment]
参考 http://www.oneplusbbs.com/thread-5495264-1.html

**Comment by snakwu** [comment]
@ndroi  我安装其他的应该没有这个问题的
