### ISSUE TITLE
how to filter https domains

### ISSUE THREAD

**Issue by NewBugger** [ndroi/easy163#5]
https://github.com/ndroi/easy163/blob/41622265533cfee8041bcca88c892ec809aef996/Easy163/app/src/main/java/org/ndroi/easy163/core/Server.java#L28-L38

music.163.com and interface.music.163.com is mostly connected domains, why are you filtered them.

i've planned to filter those https request to bypass UnblockMusic entry, to solve some problem due to cannot downgrade those https connection to http on java code, refer: https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422

**Comment by ndroi** [comment]
This code is not used, and in fact, i blocked all https requests.
blocking https force the client to downgrade to http, so i can hook the requests.

**Comment by NewBugger** [comment]
if Netease Music downgrade its request after https request failed ?

**Comment by ndroi** [comment]
yes

**Comment by NewBugger** [comment]
as i known, nondanee uses MITM in his script, what about your Java implementation?

**Comment by ndroi** [comment]
android vpn service.
parse from ip packet to tcp and then to http.

**Comment by NewBugger** [comment]
>> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)

got it.
