### ISSUE TITLE
打开网易云会自动关闭easy163

### ISSUE THREAD

**Issue by miaotianmiaodi** [ndroi/easy163#53]
网易云7.2.24
easy163 1.7.6
系统安卓11 miui12

**Comment by miaotianmiaodi** [comment]
发现好像点下载的时候会关闭，不点下载没问题

**Comment by ndroi** [comment]
下载什么，音源是什么

**Comment by miaotianmiaodi** [comment]
> 下载什么，音源是什么

又测试了一下，好像不是下载问题，是有几个音乐一点进去，easy163就会自动退出或者服务会显示关闭。比如《ebullient future》   《euphoric field》，我看服务关闭前输出的信息是全网未找到资源。

**Comment by ndroi** [comment]
这些是网易云独家收费的，修复了崩溃也没用

**Comment by meiMingle** [comment]
还是希望大佬百忙之中修复一下这个问题，‘全网未找到资源’也别让服务关闭呀。

**Comment by ndroi** [comment]
> 还是希望大佬百忙之中修复一下这个问题，‘全网未找到资源’也别让服务关闭呀。

给个歌曲名，我这边不会关闭啊

**Comment by meiMingle** [comment]
> > 还是希望大佬百忙之中修复一下这个问题，‘全网未找到资源’也别让服务关闭呀。
> 
> 给个歌曲名，我这边不会关闭啊

歌曲：《生如夏花》
![image](https://user-images.githubusercontent.com/39942874/94359287-c4d28900-00d8-11eb-8777-16f9b0719d21.png)
            《Five Hundred Miles》
![image](https://user-images.githubusercontent.com/39942874/94359306-df0c6700-00d8-11eb-9201-72bea83fffa1.png)
系统：Android 9  /    ColorOS V6.0
网易云音乐版本：官方 V6.0.0.573053     、极速版 V1.0.0.972804

**Comment by ndroi** [comment]
> > > 还是希望大佬百忙之中修复一下这个问题，‘全网未找到资源’也别让服务关闭呀。
> > 
> > 
> > 给个歌曲名，我这边不会关闭啊
> 
> 歌曲：《生如夏花》
> ![image](https://user-images.githubusercontent.com/39942874/94359287-c4d28900-00d8-11eb-8777-16f9b0719d21.png)
> 《Five Hundred Miles》
> ![image](https://user-images.githubusercontent.com/39942874/94359306-df0c6700-00d8-11eb-9201-72bea83fffa1.png)
> 系统：Android 9 / ColorOS V6.0
> 网易云音乐版本：官方 V6.0.0.573053 、极速版 V1.0.0.972804

你试下最新版的，我这边没问题

**Comment by meiMingle** [comment]
我现在用的easy163版本是 1.8.0

**Comment by meiMingle** [comment]
我先换旧版本试试吧

**Comment by meiMingle** [comment]
@ndroi   大佬，或许这个issue可以关闭了。现在用1.8.6版本的easy163已经没再出现此问题。网易云音乐版本：官方 V6.0.0.573053 、极速版 V1.0.0.972804

**Comment by ndroi** [comment]
> @ndroi 大佬，或许这个issue可以关闭了。现在用1.8.6版本的easy163已经没再出现此问题。网易云音乐版本：官方 V6.0.0.573053 、极速版 V1.0.0.972804

OK
